"""Exact public bundle allowlist; no directory globs or private project files."""
PUBLIC_FILES = (
    'index.html',
    'privacidade/index.html',
    'para/empreendedores/index.html',
    'para/creators/index.html',
    'para/consultorias/index.html',
    'para/agencias/index.html',
    'para/advocacia/index.html',
    'assets/segments.css',
    'assets/measurement.js',
    'assets/measurement-config.js',
    'assets/experience.css',
    'assets/experience.js',
    'assets/ribbon-scene.js',
    'assets/infographics.js',
    'assets/infographics.js.LEGAL.txt',
    'assets/infographics-LICENSE.txt',
    'assets/platforms/buzz.svg',
    'assets/platforms/openclaw.svg',
    'assets/platforms/hyperagent.svg',
    'assets/platforms/hermes.png',
    'assets/vendor/three-0.185.1/three.module.min.js',
    'assets/vendor/three-0.185.1/three.core.min.js',
    'assets/vendor/three-0.185.1/LICENSE.txt',
    'assets/icons/lucide/LICENSE.txt',
)
